### ISSUE TITLE
I have a few questions/requests

### ISSUE THREAD

**Issue by GazbonicAcid** [ThunderModder/bionisation3#3]
[I have a few questions/requests](https://minecraft.curseforge.com/projects/bionisation-3?comment=49).

First, can I make an immunity Symbiont of a custom virus I made with the virus creation system?

Second, can I set certain armor and armor combinations (of other mods) as a "third party" air-spread virus protection armor, such as gas mask items that protect on their own, and armor sets that require the set to protect against such things?

Third, I would like to request that you add [GasPunk](https://minecraft.curseforge.com/projects/gaspunk) integration to allow for making gas vials/grenades/[this-addons-inhalers](https://minecraft.curseforge.com/projects/gaspunk-inhaler) of Bionisation virus's/vaccines/Symbionts?

Due to the custom stuff in Bionisation I can't just add it to GasPunk myself, as it requires a specific potion id (I don't know how to add non-potion stuff as a GasPunk agent).

I am considering adding this mod to my modpack, and changing its name for the theme I've started doing.

The first and third things won't negatively impact my dission.

However I will only add it if the armor-protection thing of the second request is added or already-in.

**Comment by ThunderModder** [comment]
Hi! This is very interesting questions and requests.
About first. Currently no, but this is really good idea and i will add this in next update.
About second. It will be hard to add, because it needs a compatibility with all mods that add gasmasks and other similar stuff. I will try to do something.
About third. I will see what i can do with this mod. Adding a lot of potions will disrupt the compatibility with other mods. Thats why Bionisation is using its own effect system.
Thanks a lot for your feedback!

**Comment by ReidenXerx** [comment]
Hello
I would like to solve some problems

1. Virus, which gives mobs immortality is very annoying, because immortal mobs with good weapons in my modpack give very bad effects for gameplay
2. Creepers infected by virus blow up without anyone`s help
its too very annoying and hazardous for gameplay, because it corrupts landscape and increases loadout on server

Please, help me with this issues, because your mod is really interesting but with this problems we cant use it on our server

Sorry for not really good english

**Comment by ThunderModder** [comment]
@ReidenXerx Hi! Look at config file. There you can disable any effect you want :)

There are no viruses that give immortality, only health and strength boost. So may be you need to disable Giant virus. Also there are no viruses to instantly blow up a creeper. But there are effects that can make any mob agressive and if they will attack creeper it will blow up(Red virus, Brain virus, Rabies).

**Comment by GazbonicAcid** [comment]
I assume closing this meant you've decided on whether to add it or not?
If so, are you planning on implementing the features I asked for?
If yes, please let me know when the version with it is released.

**Comment by ThunderModder** [comment]
@GazbonicAcid Im trying to implement all of your ideas. Currently i dont know when the next version will be released, but i will try to do it as soon as i can.
